### PR TITLE
Slim ST_PATS board

### PR DESCRIPTION
**Pull request by Rio6**
Slimmer board for st-pat

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/st_pats/4)

### CODE REVIEW

**Comment by Rio6** [comment]
I just realized I completely forgot to add the receivers :p

**Comment by Rio6** [comment]
Added the telemetry board.

**Review by zx100x100 — CHANGES_REQUESTED** [review]
Overall looking dope!!! a few notes:
Biggest thing: I think we really need some mech CAD here, there are half a dozen different boards, all potentially with fasteners here. I'd like to see a CAD model of the complete system before proceeding to make sure there are no interface concerns. I also suspect that as you nail down the enclosure design you will find some things need to move. (for example right now the radio antennas go where I think I would want to hold it. It is ok if it ends up wider, this thing is absolutely tiny right now.

GPS is upside down right now, it likes looking at the sky :sadparrot:

You've called out a M0 proto on the schematic, we want to use a M0 logger version.

I believe P2_8 is the battery monitoring pin, would be good to add a note to the schematic so no one tries to use it for something else in the future.

Hella nitpicky I know, but could we rename the folder to schematics or something? No need to limit the name to two characters. 'hw'

might be worth renaming these to gps_rx and gps_tx, but no biggie:
image

what's going on here with the IMU? 
image

Can you please add silkscreen labels for everything so it's easier to tell what's what? (especially the buttons and LEDs)

Overall your routing and schematic are on point, but there is some overall system layout stuff we need to work out. :fantasticstuff:

**Comment by Rio6** [comment]
圖片
How's this layout.

I'm not sure what's with the IMU, will have to double check with the official footpring. Might just need to shrink the outer circle a bit.

**Comment by dwkletke** [comment]
I think overall it looks really nice! I could see the edge of the telemetry breakout board (U6) being a bit close to the mount hole that you might not be able to fit certain screws/nuts but it probably isn't too big of a deal.
image

Also, being a bit nitpicky but the reset button (SW2) is oriented sideways with respect to the reset of the components, so just make sure when you put the silkscreen label for it that it is in the same orientation as the rest of the components/labels!
image

**Comment by Rio6** [comment]
圖片
Spaced things out a bit more. And I moved a few Fab text to SilkS (LEDs, reset button, and board names).

About Proto vs Datalogger: their pins are the same afaik. The added SD card slot only used the unused pins.

**Review by BluCodeGH — COMMENTED** [review]
Looking good!
1. Did you mean to have the adafruit compass overlapping with one of the telemetry breakout boards? It looks like there's room for it on the other side of the PCB.
2. Given that the schematic (and likely the code) will differentiate between the SRAD and COTS telemetry breakouts, I'd suggest doing the same on the silkscreen so there are no confusing assembly errors.

**Comment by Rio6** [comment]
Wait did I really put the compass on the wrong side? Yeah that's meant to be on the other side.

I'll update label for the telemetry boards

**Review by BluCodeGH — APPROVED** [review]
LGTM!

**Comment by Rio6** [comment]
Some changes:

- Replaced GPS module with breakout board that we already have
- Replaced buttons with more common ones
- Disconnected the reset button from telemetry breakouts because I realized their reset pin is active high while the reset pin for the feather is active low :p

**Review by zx100x100 — APPROVED** [review]
Looks good to me, next step is to generate the Gerber files so we can order the boards

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
It seems that this silkscreen is slightly overlapping with the pad. Could move it a bit away. 
image

Once that's done, LGTM!

**Review by QuantumManiac — APPROVED** [review]

**Comment by BluCodeGH** [comment]
Hardware has been ordered, good to merge.

**Pull request merged**
