### PR TITLE
ST_PATS v2.1

### PR DESCRIPTION
**Pull request by Rio6**
image

Update live telemetry breakout footprint and remove aprs srad receiver

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/st_pats/5)

### CODE REVIEW

**Review by BluCodeGH — APPROVED** [review]
Looks good!
If you need to make changes based on other reviews I'd add silkscreen labels saying which direction of the switch is on and off, and fix this tight corner
image
Also is this lone via intentional?
image

**Comment by Rio6** [comment]
1. FIxed
2. The via isn't required but DRC/ratnet complains without it. Although I found another way to route the lines without DRC complaining so I removed the via now

**Comment by Rio6** [comment]
for switch: I'm not sure which is on or off either :sweat_smile:, I'll have to multimeter it

**Comment by ZTeper** [comment]
Check whether the TELE_TX, TELE_RX are connected to the correct pins on the Feather. Not all Feather pins support UART.

**Review by ZTeper — CHANGES_REQUESTED** [review]
Check that the PA19, PA16 pins support UART, or attach the live telemetry interface to different pins.

**Review by ZTeper — APPROVED** [review]

**Review by QuantumManiac — APPROVED** [review]
LTGM. Add dimensioning for the board length/width and spacings between mounting holes if desired.

**Comment by Rio6** [comment]
> Check that the PA19, PA16 pins support UART, or attach the live telemetry interface to different pins.

I checked it. From the variant code I found for Adafruit Feather M0, sercom0 is USB Serial, sercom3 is I2C, sercom4 is SPI, sercom5 is Serial1 on TX/RX pins. So sercom1 and sercom2 are available. The datasheet shows PA16 and PA19 can be used on sercom1 so I used those two.

image

**Comment by Artem-Sotnikov** [comment]
The board looks great! I do have a few comments, but we shouldn't delay ordering it. These comments are on things that could possibly be improved in a future respin, and thus I'll note them down here anyway. 

1. Silk screens on some of the important pins are a nice-to-have that could make a debugger's job easier.
2. Silk screens for boards should be placed outside the footprints so that they can be visible even after the board is mounted.

**Review by Artem-Sotnikov — APPROVED** [review]

**Comment by BluCodeGH** [comment]
Ordered, merging.

**Pull request merged**
