### PR TITLE
Stpats 2.1

### PR DESCRIPTION
**Pull request by Rio6**
Code for new stpats. Documentation here https://uwaterloo.atlassian.net/wiki/spaces/ROCKETRY/pages/43040375798/ST+PATS+2.1+Usage

I removed the old sources from the branch, as git keeps tracks of them already.

I'm using PlatformIO to build the code since it's easier to track dependencies with it. But Arduino IDE *should* compile them as well.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/st_pats/6)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks pretty well written, mostly just needs some comments.

> Reviewed 34 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/st_pats/6#-:-N2PNGlcCSRj9-5oeALW:bt2w41z)* status: all files reviewed, 5 unresolved discussions (waiting on @jlsajfj, @QuantumManiac, @Rio6, @ZTeper, and @zx100x100)

___
*[`src/compass.cpp` line 154 at r1](https://reviewable.io/reviews/waterloo-rocketry/st_pats/6#-N2PJuZ3BNzCxY02aqeG:-N2PJuZ3BNzCxY02aqeH:b-hfpv1m) ([raw file](https://github.com/waterloo-rocketry/st_pats/blob/ee37ed4d4c176eab1cd72d50df63b91d229a02f5/src/compass.cpp#L154)):*
> ```cpp
> 
>    /*
>    // debug circle
> ```

remove?
___
*[`src/compass.cpp` line 163 at r1](https://reviewable.io/reviews/waterloo-rocketry/st_pats/6#-N2PJxehEsLwfWCGx6Co:-N2PJxehEsLwfWCGx6Cp:b-7uetid) ([raw file](https://github.com/waterloo-rocketry/st_pats/blob/ee37ed4d4c176eab1cd72d50df63b91d229a02f5/src/compass.cpp#L163)):*
> ```cpp
> 
>    // draw current heading
>    {
> ```

Why is this bit wrapped in braces?
___
*[`src/util.h` line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/st_pats/6#-N2PEpcDC2By-5Q_G0ov:-N2PEpcDC2By-5Q_G0ow:b-q85zxf) ([raw file](https://github.com/waterloo-rocketry/st_pats/blob/ee37ed4d4c176eab1cd72d50df63b91d229a02f5/src/util.h#L6)):*
> ```objc
> }
> 
> inline float heading_from(float olat, float olon, float tlat, float tlon) {
> ```

Could use some comments saying what these functions do
___
*[`utils/aprs2stpats.py` line 12 at r1](https://reviewable.io/reviews/waterloo-rocketry/st_pats/6#-N2PI1ct-mfKsv6pvoDe:-N2PI1ct-mfKsv6pvoDf:b-zeyejr) ([raw file](https://github.com/waterloo-rocketry/st_pats/blob/ee37ed4d4c176eab1cd72d50df63b91d229a02f5/utils/aprs2stpats.py#L12)):*
> ```Python
> DEBUG = False
> 
> def parse_aprs(data):
> ```

I'd really like some comments with what data format this is supposed to be parsing
___
*[`utils/aprs2stpats.py` line 62 at r1](https://reviewable.io/reviews/waterloo-rocketry/st_pats/6#-N2PHGbF-09SXKhIo9ph:-N2PHGbF-09SXKhIo9pi:b-y0mv9n) ([raw file](https://github.com/waterloo-rocketry/st_pats/blob/ee37ed4d4c176eab1cd72d50df63b91d229a02f5/utils/aprs2stpats.py#L62)):*
> ```Python
> 
> def main():
>     parse_args()
> ```

Please use the `argparse` module, it's built in and handles this all for you.

**Comment by Rio6** [comment]
I kept the debug circle code because it might be useful again when debugging in future. Fixed other issues.

Also added a README.md

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Sounds good, one last tweak and we're good.

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/st_pats/6#-:-N2gmaxRBUbWA7pzwAd9:b-swqsp4)* status: all files reviewed, 1 unresolved discussion (waiting on @jlsajfj, @QuantumManiac, @Rio6, @ZTeper, and @zx100x100)

___
*[`utils/aprs2stpats.py` line 10 at r3](https://reviewable.io/reviews/waterloo-rocketry/st_pats/6#-N2gmB5TAZu31ybsJKiw:-N2gmB5U4-rmppDT_GYd:b-y5gr2w) ([raw file](https://github.com/waterloo-rocketry/st_pats/blob/aab7a5c3ac4d38a0ffab24c61fc9f59618189988/utils/aprs2stpats.py#L10)):*
> ```Python
> 
> # parse APRS AX.25 KISS frames into aprspy classes
> def parse_aprs(data):
> ```

Rather than `global args` pass a debug flag as an argument (since that is the only argument used here)

**Comment by Rio6** [comment]
fixed

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/st_pats/6#-:-N2lqMrI52UZHLwJC4L4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jlsajfj, @QuantumManiac, @ZTeper, and @zx100x100)

**Pull request merged**
